### ISSUE TITLE
Implement action masks

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#110]
The ActionMask classes have a `mask` field that in principle allows masking out specific action choices, but this is currently ignored by all action heads.

**Comment by Bam4d** [comment]
@cswinter So in my understanding the action masks for SelectEntity are dealt with by the masked transformer. The "actors" and "actees" make up the equivalent masking operation? Or is there another level there that I am missing?

**Comment by cswinter** [comment]
Yeah there is another level, say we have actors A1, A2, A3 and actees B1, B2, B3. Currently, any actor can select any unit, but but imagine e.g. a ranged ability where not all actees are in range of very actor. Them we might want to allow A1 to select any of B1, B2, B3, but allow A2 and A3 to only select B2 or B3. This would require an additional action mask of size actors x actees. I don't think we need this for anything yet.

**Comment by Bam4d** [comment]
Just to clarify: 
Currently in our select entity action for action `ranged_ability`, we would have actors==[A1,A2,A3] and an actees==[B1,B2,B3].
The environment would then need to provide the mask:
```
[
  #B1 B2 B3
  [ 1,   1,   1] #A1
  [ 0,   1 ,  1] #A2
  [ 0,   1 ,  1] #A3
]
```

I can probably think up a simple griddly environment that would require this,, but do we want to do it as part of the other ticket or should it live in its own ticket?

**Comment by cswinter** [comment]
Yes, that's right. I think it makes sense to do it in a separate PR. The whole select-entity action head is quite fiddly, we'll also want a test that checks that a random policy never selects any of the actor/actee combinations we are masking.
