### ISSUE TITLE
Fix crash on empty observation

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#128]
Something doesn't work with 0-element observations: https://github.com/entity-neural-network/incubator/pull/123#issuecomment-1003631910

**Comment by cswinter** [comment]
Curiously enough, we do have some environments that occasionally export empty observations, e.g. https://github.com/entity-neural-network/incubator/blob/cdef2b7d2e6c9bf6208dd7ca561aaaa2bb27fbb9/entity_gym/entity_gym/envs/not_hotdog.py#L72-L82

It does require being a little careful about the shape of the zero-size tensor, so that might be what @vwxyzjn ran into. If that's the case we should still improve the error message though.

**Comment by Bam4d** [comment]
Is this similar where you have to set empty tensors with '.reshape(-1, 0)' ?

**Comment by cswinter** [comment]
Probably similar, it's kind of dumb that `np.zeros((0, 1), dtype=np.float32)` doesn't actually have a shape of `(0, 1)`.

**Comment by cswinter** [comment]
Oh actually that's fake news, it does have a shape of `(0, 1)`, not sure why the reshape is there then. I remember there being some annoyingness with empty tensors, but the fix must have been something else then.

**Comment by cswinter** [comment]
This is probably fixed.
