### ISSUE TITLE
[BUG] Errors on non-sequential entity IDs in training

### ISSUE THREAD

**Issue by vwxyzjn** [entity-neural-network/incubator#155]
Hello, reporting a bug here. The current implementation seems to assume sequential entity IDs. 

In #123, I have the following observations:

![image](https://user-images.githubusercontent.com/5555347/150704156-ce134f9e-c893-4810-a559-edfafd32d17c.png)

where the entities have IDs `[4, 5, 6, 7, 8, 9, 10, 11]` and the entities have mask `[ 8 10]`. I can use the `main.py` to interact with the games to harvest resources.

However, there is an issue during training. Basically, the mask `[ 8 10]` is used to select `actor_embeds`, however, the idx 8 and 10 are out of bounds for the ` x.data`, which only has embeddings corresponding to 8 objects. 

![image](https://user-images.githubusercontent.com/5555347/150704292-9035586d-f738-41ed-be0c-a48ec5a97c70.png)

**Comment by cswinter** [comment]
I think the code assumes that `actors` is the index of the entity rather than the id, so in this case, it would probably work as expected if `actors` is `[4, 6]` instead. Using ids for `actors` might be more convenient, we could support that API by letting train.py construct a reverse index of what id maps to what index to convert it into indices instead. Though it might be easier for the environment to just provide the indices, e.g. `[i for i, entity in enumerate(i, entity) if can_perform_action(entity)]`. But that only works if all entities are in a single list, maybe the `actors` should be split up per-entity.
The whole thing is very confusing and poorly documented, I'm going to create an issue for coming up with a better API.

**Comment by vwxyzjn** [comment]
Thanks for the quick reply. I gave it a quick try by supplying `[4, 6]`, it seems the agent can do 1 step now, but the next step the following error happened (probably because the actor mask is empty in the second step (all units are busy)):

```
(incubator-BZ1MCGMS-py3.9) ➜  enn_ppo git:(microrts) ✗ python enn_ppo/train.py --gym-id GymMicrorts --cuda False --num-envs 1
[[4]
 [6]]
torch.Size([8, 64]) torch.Size([2, 1]) tensor([[4],
        [6]])
[]
Traceback (most recent call last):
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 962, in <module>
    train(args)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 658, in train
    next_obs, next_done, metrics = rollout.run(args.num_steps, record_samples=True)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 362, in run
    next_obs = self.envs.act(_actions, self.obs_space)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/entity_gym/entity_gym/environment/env_list.py", line 56, in act
    return batch_obs(observations, self.cls.obs_space(), self.cls.action_space())
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/entity_gym/entity_gym/environment/vec_env.py", line 219, in batch_obs
    action_masks[action_name].push(o.action_masks[action_name])
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/entity_gym/entity_gym/environment/vec_env.py", line 40, in push
    self.actors.push(mask.actors.reshape(-1, 1))
TypeError: argument 'items': Shape Mismatch:
 from=(dim=2, dtype=Float64), to=(dim=_, dtype=Int64)
```

**Comment by cswinter** [comment]
It looks like the `dtype` is mismatched, you might have to explicitly cast something to the right type.

**Comment by vwxyzjn** [comment]
Yep the `dtype` was definitely one problem, but it seems the actor mask being an empty array also caused some problems 👀

```
class CategoricalActionMaskBatch:
    actors: RaggedBufferI64
    masks: Optional[RaggedBufferBool]

    def push(self, mask: Any) -> None:
        assert isinstance(mask, DenseCategoricalActionMask)
        print(mask.actors.reshape(-1, 1).astype(np.int64))
        self.actors.push(mask.actors.reshape(-1, 1).astype(np.int64))
        if self.masks is not None and mask.mask is not None:
            self.masks.push(mask.mask.reshape(-1, self.masks.size2())) 
```


```

(incubator-BZ1MCGMS-py3.9) ➜  enn_ppo git:(microrts) ✗ python enn_ppo/train.py --gym-id GymMicrorts --cuda False --num-envs 1
[[4]
 [6]]
torch.Size([8, 64]) torch.Size([2, 1]) tensor([[4],
        [6]])
[]
torch.Size([8, 64]) torch.Size([0, 1]) tensor([], size=(0, 1), dtype=torch.int64)
Traceback (most recent call last):
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 962, in <module>
    train(args)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 658, in train
    next_obs, next_done, metrics = rollout.run(args.num_steps, record_samples=True)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 330, in run
    ) = self.agent.get_action_and_auxiliary(
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/rogue_net/rogue_net/actor.py", line 166, in get_action_and_auxiliary
    action, count, logprob, entropy, logit = action_head(
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/rogue_net/rogue_net/head_creator.py", line 73, in forward
    dist = Categorical(logits=logits)
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
    valid = constraint.check(value)
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/distributions/constraints.py", line 206, in check
    result = result.reshape(result.shape[:result.dim() - self.reinterpreted_batch_ndims] + (-1,))
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 1, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by cswinter** [comment]
That looks like a bug then, maybe we need a special case there. What's the value of the `logits` getting fed into the `Categorical`?

**Comment by vwxyzjn** [comment]
```
(incubator-BZ1MCGMS-py3.9) ➜  enn_ppo git:(microrts) ✗ python enn_ppo/train.py --gym-id GymMicrorts --cuda False --num-envs 1
[[4]
 [6]]
===========logits shape and values torch.Size([2, 1, 12]) tensor([[[ 8.7851e-03,  7.6442e-03,  9.3685e-05,  4.7050e-03,  2.3091e-03,
          -5.6939e-04,  1.1391e-02, -2.2669e-03, -7.1054e-03,  1.3224e-02,
          -1.0735e-02, -7.3825e-03]],

        [[ 1.2371e-02,  1.0953e-02, -4.1577e-03,  1.5493e-03,  1.2193e-03,
           5.1339e-03,  1.1152e-02, -4.9390e-03, -7.6794e-03,  1.0422e-02,
          -9.9854e-03, -7.9820e-03]]])
[]
===========logits shape and values torch.Size([0, 1, 12]) tensor([], size=(0, 1, 12))
```

**Comment by cswinter** [comment]
Well, that's unfortunate, looks like `Categorical` just doesn't work for 0 sized batches and we'll need to add a special case.

**Comment by cswinter** [comment]
We'll probably just have to add the special case for now, but I also opened an issue with PyTorch: https://github.com/pytorch/pytorch/issues/71689

**Comment by Bam4d** [comment]
> I think the code assumes that `actors` is the index of the entity rather than the id, so in this case, it would probably work as expected if `actors` is `[4, 6]` instead. Using ids for `actors` might be more convenient, we could support that API by letting train.py construct a reverse index of what id maps to what index to convert it into indices instead. Though it might be easier for the environment to just provide the indices, e.g. `[i for i, entity in enumerate(i, entity) if can_perform_action(entity)]`. But that only works if all entities are in a single list, maybe the `actors` should be split up per-entity. The whole thing is very confusing and poorly documented, I'm going to create an issue for coming up with a better API.

I too went through this confusion with Griddly, I thought that the input was EntityID rather than index

**Comment by cswinter** [comment]
With https://github.com/entity-neural-network/incubator/pull/166 landed, the majority of encountered issues should now be eliminated. Environment validation and further errors improvements are tracked by https://github.com/entity-neural-network/incubator/issues/160.
