### ISSUE TITLE
Rethink action mask API

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#156]
# Rethink action mask API

The current API for specifying actors is very confusing and poorly documented (I myself was very confused by it after not looking at it for a month after implementing it and forgetting how it works 😆). I think we can come up with something better.

## Running example

Suppose we have an environment with two entity types, `Worker` and `Resource`, both with features `x` and `y`, a `harvest` action, and a `move` action. The observation and action spaces might look like this:

```python
obs_space = {
  "resource": Entity(["x", "y"]),
  "worker": Entity(["x", "y"]),
}
action_space = {
  "harvest": CategoricalAction(["harvest", "don't harvest"]),
  "move": CategoricalAction(["up", "down", "left", "right"]),
}
```

Suppose that on a particular timestep, we have two resource entities `r1` and `r2`, and three worker entities `w1`, `w2`, and `w3`. Only `w1` and `w3` can perform the `harvest` action on this timestep. All resources and workers can perform the `move` action, but `w2` can't move `down` or `left`.

## Observations

Observations are currently defined like this:

https://github.com/entity-neural-network/incubator/blob/c887f4a2f6601c67e8feb03ba9b16f27f74a223f/entity_gym/entity_gym/environment/environment.py#L82-L92

### `entities`

The observation consists of a dictionary mapping each entity type to a numpy array with the features of all entities of that type:

```python
entities = {
  "resource": [
    [10, 4], # r1
    [11, 6], # r2
  ],
  "worker": [
    [10, 4], # w1
    [0, 0],  # w2
    [11, 6], # w3
  ],
}
```

This seems fine, or at least I can't think of any obvious simplification or more ergonomic API.

### `ids`

The `ids` are meant to allow the environment to designate an opaque identifier for each entity, which then makes it easy to later lookup that entity when executing actions chosen by the policy. For example, we could use the following list of strings to identify our entities:

```python
ids = ["r1", "r2", "w1", "w2", "w3"],
```

In practice, this mostly adds runtime overhead and API complexity, and it's unclear whether it is actually particularly useful for most environments. One issue is also that the correspondence between the `ids` and entities is not obvious since it relies on the implicit ordering of entity types defined by the observation space.

### `action_masks`

The environment must specify which entities can perform each action. This is done by returning an `ActionMask` for each action that specifies an `actors` list that specifies the indices of the entities that can perform the action:

```python
action_masks = {
  "harvest": DenseCategoricalActionMask(actors=[2, 4]),
  "move": DenseCategoricalActionMask(
    actors=[0, 1, 2, 3, 4],
    mask=[
      [True, True, True, True],
      [True, True, True, True],
      [True, True, True, True],
      [True, False, False, True],
      [True, True, True, True],
    ],
  ),
}
```

The `actors` field is very unintuitive. In contrast to the observation, it's a single list rather than a list per entity, and it relies on the implicit ordering of entity types given by the observation space dictionary. The `mask` is also inconsistent with the `ids`, since it uses indices rather than the `ids` to specify actors.

### `action`

Once we have sampled actions from the policy, we call the `step` method again and supply a `action: Mapping[str, Action]` with the choices made by the policy for each action. For categorical actions, this is represented by a `actions: List[Tuple[EntityID, int]]` which pairs each actor with the index of the chosen action:

```python
actions = {
  "move": CategoricalAction([
    "r1": 0,
    "r2": 0,
    "w1": 2,
    "w2", 0,
    "w3", 3
  ]),
  "harvest": CategoricalAction([
    "w1": 0,
    "w3": 3,
  ]),
}
```

## Solutions

The current API is pretty bad, not sure what the best solution is but here are some ideas:

### Proposal 1: Group `action_masks` and `ids` by entity type

The indices would now be per entity, corresponding to the features in `entities`. This would make it a little more obvious what's going on. And in the common case of all entities of some type being able to execute an action, we wouldn't need to specify the `actors` field at all.

```python
action_masks = {
  "worker": {
    "harvest": DenseCategoricalActionMask(actors=[0, 2]),
    "move": DenseCategoricalActionMask(
      mask=[
        [True, True, True, True],
        [True, False, False, True],
        [True, True, True, True],
      ],
    ),
  },
  "resource": {
    "move": DenseCategoricalActionMask(
      mask=[
        [True, True, True, True],
        [True, True, True, True],
      ],
    )
  },
}

ids = {
  "worker": ["w1", "w2", "w3"],
  "resource": ["r1", "r2"],
}
```

### Proposal 2: Use `EntityID`s to specify `actors`

Instead of indices, use `EntiyID`s for `actors`:

```python
action_masks = {
  "harvest": DenseCategoricalActionMask(actors=["w1", "w2"]),
  "move": DenseCategoricalActionMask(
    actors=["r1", "r2", "w1", "w2", "w3"],
    mask=[
      [True, True, True, True],
      [True, True, True, True],
      [True, True, True, True],
      [True, False, False, True],
      [True, True, True, True],
    ],
  ),
}
```

### Proposal 3: Just get rid of `ids`

The `EntityID`s haven't proved particularly useful so far. We could just get rid of the `ids` field and remove the `EntityID` from the actions passed to `act`. Something similar to the old interface that works with environment-supplied ids rather than indices could still be achieved with an env wrapper or helper methods.

```python
actions = {
  "move": CategoricalAction([0, 0, 2, 0, 3]),
  "harvest": CategoricalAction([0, 3]),
}
```

If combined with (1):

```python
actions = {
  "worker": {
    "move": CategoricalAction([2, 0, 3]),
    "harvest": CategoricalAction([0, 3]),
   },
  "resource": {
    "move": CategoricalAction([0, 0]),
  },
}
```

**Comment by vwxyzjn** [comment]
> This seems fine, or at least I can't think of any obvious simplification or more ergonomic API.

Yeah, I agree. The observation scheme is perfectly fine to me :)  

> and it's unclear whether it is actually particularly useful for most environments

Would you mind elaborating on this?

>  One issue is also that the correspondence between the ids and entities is not obvious since it relies on the implicit ordering of entity types defined by the observation space.

I'd say the API should only rely on the unique IDs themselves. Each id exactly corresponds to a live entity. An edge case is if an entity is dead, we should still enforce different entity IDs because the dead and live entities sharing the same IDs may cause confusion to the training algorithm.

The implicit ordering seems problematic. 

> we wouldn't need to specify the actors field at all.

Did you mean

```diff
 action_masks = {
   "worker": {
-   "harvest": DenseCategoricalActionMask(actors=[0, 2]),
+   "harvest": DenseCategoricalActionMask(
+        mask=[
+            [True, True],
+            [True, True],
+        ]
+    ),
     "move": DenseCategoricalActionMask(
       mask=[
         [True, True, True, True],
         [True, False, False, True],
         [True, True, True, True],
       ],
     ),
   },
   "resource": {
     "move": DenseCategoricalActionMask(
       mask=[
         [True, True, True, True],
         [True, True, True, True],
       ],
     )
   },
 }
```

> Proposal 3: Just get rid of ids

How does this handle the masking issues?

**Comment by cswinter** [comment]
> > and it's unclear whether it is actually particularly useful for most environments
> 
> Would you mind elaborating on this?

I've found that in the environments I've implemented so far, entities can already naturally be iterated through in the same order as done to create features/action masks, so having the entity id for each action doesn't make the environment easier to implement since it's just ignored anyway, e.g.: https://github.com/entity-neural-network/incubator/blob/4001598e59e02276f398dd990d1f1ff42a180107/enn_zoo/enn_zoo/codecraft/vec_env.py#L433-L438

> > One issue is also that the correspondence between the ids and entities is not obvious since it relies on the implicit ordering of entity types defined by the observation space.
> 
> I'd say the API should only rely on the unique IDs themselves. Each id exactly corresponds to a live entity. An edge case is if an entity is dead, we should still enforce different entity IDs because the dead and live entities sharing the same IDs may cause confusion to the training algorithm.

Yeah, that's a good point I hadn't thought of before. Doesn't matter in the current implementation, if we want to implement something like per-entity memory, we need to be able to track identities across timesteps.

> > we wouldn't need to specify the actors field at all.
> 
> Did you mean
> 
> ```diff
>  action_masks = {
>    "worker": {
> -   "harvest": DenseCategoricalActionMask(actors=[0, 2]),
> +   "harvest": DenseCategoricalActionMask(
> +        mask=[
> +            [True, True],
> +            [True, True],
> +        ]
> +    ),
>      "move": DenseCategoricalActionMask(
>        mask=[
>          [True, True, True, True],
>          [True, False, False, True],
>          [True, True, True, True],
>        ],
>      ),
>    },
>    "resource": {
>      "move": DenseCategoricalActionMask(
>        mask=[
>          [True, True, True, True],
>          [True, True, True, True],
>        ],
>      )
>    },
>  }
> ```

On the "move" action, the `actors` field can be omitted since all entities of that type are performing the action. On the "harvest" action, we set `actors=[0, 2]` to specify that only the first and third worker entity can perform the action, and the `mask` can be omitted since all choices are available. 

> > Proposal 3: Just get rid of ids
> 
> How does this handle the masking issues?

Mostly it would just simplify the API for environments that don't care about getting an `EntityID` associated with each action. Selecting `actors` would be by index as done currently (but probably grouped by entity type).

**Comment by Bam4d** [comment]
My thoughts:

when I implemented the Griddly wrapper, I was very confused between EntityID and Index. It was unclear which one should be used where. I actually implemented my wrapper first using Proposal 2 (thinking this is how it was set up). 

I then tried to make the API do the unwrapping back to IDs but this ended up being super problematic because keeping track of entity-to-id maps was complex especially in complex environments where the entities change per-frame. Essentially you would need to keep rebuilding this map.

> I've found that in the environments I've implemented so far, entities can already naturally be iterated through in the same order as done to create features/action masks
Instead what I did was generate a unique hash for each entity and then always order by that hash. this way the index to unique ID is always consistent and it removes the requirement for there to be some mapping because the order of the mapping is the same as the index. I had to fix a bunch of stuff to get this to work (I'm fairly convinced this is bug free as i wrote a bunch of tests for it)

> if we want to implement something like per-entity memory, we need to be able to track identities across timesteps.
Additionally we have to think about how this works when things get batched and have diffent numbers of entities in each observation. The indexes/masking still needs to be consistent across the whole batch using ragged buffers etc. I ended up writing some tests after fixing how this worked: https://github.com/entity-neural-network/incubator/blob/main/entity_gym/entity_gym/tests/test_environment.py

Proposal 1 does not fix the ordering issue within the groups.. so there still needs to be some way to match the order of masks to entities.

Proposal 2 has the issue of mapping that I came across above and while I'm sure this can be done, the environment still needs to provide a index mapping, or have one calculated per frame to be consistent with changable environments.

Proposal 3... again same issue with 1 and 2, the mapping still needs to be solved.

## Proposal 4:

To make the environment super friendly and obvious (but probably bit less efficient) I would think and API for masks thats mapped per-entityID is the most intuitive to build as an environment integrator. It also relies on the mapping function in proposal 2... but means that the environments don't have to worry about the ordering or mapping function (because its hidden away internally):

a)
```
{
  "r1": {
    "move": [True, True, True, True]
  },
  "r2": {
    "move": [True, True, True, True]
  },
  "w1": {
    "move": [True, True, True, True],
    "harvest": [True, True]
  },
  "w2": {
    "move": [True, False, False, True]
  },
  "w3": {
    "move": [True, True, True, True],
    "harvest": [True, True]
  }
}
```

b)
```
{
  "move": {
    "r1": [True, True, True, True],
    "r2": [True, True, True, True],
    "w1": [True, True, True, True],
    "w2": [True, False, False, True],
    "w3": [True, True, True, True]
  },
  "harvest": {
    "w1": [True, True],
    "w3": [True, True]
  }
}
```

This 
1) Enforces the requirement of the unique ID in the environment.
2) Makes it pretty impossible for the environment to supply incorrect indexed masks because it's all calculated underneath.
3) b) This matches the action API making things even easier to understand

Internally we can just order the unique ids every frame (this happens internally in Griddly) and then just keep that order consistent when we calculate the indexes.

**Comment by cswinter** [comment]
Thanks for all the input! It sounds like we already have general consensus on two points:

1. We should keep `EntityID`s and always use `EntityID`s rather than indices
2. The `ids` should be grouped by entity type, same as `entities`

@Bam4d In Proposal 4, would you also group the entities by ID? So do something like this:

```
entities = {
  "resource": {
    "r1": [10, 4],
    "r2": [11, 6], # r2
  },
  "worker": {
    "w1": [10, 4],
    "w2": [0, 0],
    "w3": [11, 6],
  },
}
```

Then you wouldn't need the `ids` field since it's now merged with `entities`, and the `entities` work 

I do think this would limit performance, especially for environments with many entities, but that's not necessarily a problem since we can still have a less ergonomic but more efficient alternative API.

The most ergonomic version I can think of that is still efficient would be to combine proposals 1 and 2:

```
ids = {
  "worker": ["w1", "w2", "w3"],
  "resource": ["r1", "r2"],
}

entities = {
  "resource": [
    [10, 4], # r1
    [11, 6], # r2
  ],
  "worker": [
    [10, 4], # w1
    [0, 0],  # w2
    [11, 6], # w3
  ],
}

action_masks = {
  "worker": {
    "harvest": DenseCategoricalActionMask(actors=["w1", "w3"]),
    "move": DenseCategoricalActionMask(
      # if actors is omitted, we implicitly have actors = ids["worker"] = ["w1", "w2", "w3"]
      mask=[
        [True, True, True, True],
        [True, False, False, True],
        [True, True, True, True],
      ],
    ),
  },
  "resource": {
    "move": DenseCategoricalActionMask(
      mask=[
        [True, True, True, True],
        [True, True, True, True],
      ],
    )
  },
}
```

This ought to be convenient for environments, e.g. I imagine in most cases you could do something like this:

```python
for entity_type in entity_types:
  for id, entity in entities[entity_type]:
    for action_type in entity.action_types():
      action_masks[entity_type][action_type].append(entity.mask())
    ids[entity_type].append(id)
    features.append(entity.features())
```

Or this:

```
for entity_type in entity_types:
  for id, entity in entities[entity_type]:
    ids[entity_type].append(id)
    features.append(entity.features())
actors = []
masks = []
for id, entity in all_entities:
  if entity.can_act():
    actors.append(id)
    masks.append(entity.mask())
```

**Comment by vwxyzjn** [comment]
Quick nit: Why couldn't we just combine the `DenseCategoricalActionMask(actors=` and `DenseCategoricalActionMask(mask=` together?

The `actors` mask feels like a special case for `mask`. You would simply have an action space that look like

```
action_space = {
  "harvest": CategoricalAction(["noop", "harvest"]),
  "move": CategoricalAction(["noop", "up", "down", "left", "right"]),
}
```

and if the entity cannot perform an action, we simply mask out everything except `noop`. In gym-micrrorts, we adopted this paradigm.

**Comment by cswinter** [comment]
That's a good point. If the actors are very sparse, there's might be some efficiency gains, but they're probably fairly minor, especially if we're going to partition the masks by entity type.
I'm still leaning towards keeping the `actors` since it might still be the more natural/efficient API in some cases, but make it so you can also specify just the mask (or neither) and have that be the default.

**Comment by cswinter** [comment]
I've created a draft of a revised API, which I'm thinking of as a starting point for further discussion: https://github.com/entity-neural-network/incubator/pull/166
It includes [a new tutorial on how to implement an Environment](https://github.com/entity-neural-network/incubator/blob/clemens/environment-api-redesign/entity_gym/TUTORIAL.md). Let me know what you think!

Some high-level comments:
- The API doesn't stray too far from the previous structure, with the main difference being that `Environment` does not deal with indices anymore and everything uses `EntityID`s instead. It would now be very straightforward though to add alternative constructors for `Observation` that expose an interface more similar to e.g. "Proposal 4" and just do a little bit of straightforward translation.
- The `Environment` is now optimized for an ergonomic interface, and `VecEnv` is optimized for an efficient interface. I tried to find some middle ground for some time (e.g. similar to previous `VecEnv` where all features are combined in a ragged buffer, but we still use `EntityID`s as opposed to indices) but what I was able to come up with was neither efficient nor ergonomic and also just kind of inconsistent. The clear separation between efficient and ergonomic interfaces we have now seems cleaner, and since most people won't have to implement `VecEnv` themselves it should be fine for that interface to be a bit more complicated.
- There are still no provisions for tracking entities across timesteps. I think this will add quite a bit of additional complexity (for implementation and `VecEnv` interface, but not the `Environment` interface)  and the correct data structures aren't clear to me yet. This will likely be a substantial project of its own and is probably best tackled at a later time.

**Comment by vwxyzjn** [comment]
Hey, @cswinter this new API mask sense to me. The tutorial is super helpful. A couple of nit questions: 
1. Do the ids have to be integers?
2. Do the ids have to be sequential (i.e. can it be 4, 7, 1, -4)

**Comment by Bam4d** [comment]
> 1. Do the ids have to be integers?

From the tests, this is not the case, the IDs in the tests are strings.

**Comment by cswinter** [comment]
The IDs have to obey the following constraints (should probably be added to docs):
- Serializable by numpy_msgpack
- Hashable
- Unique (on that timestep)
So e.g. something like `Tuple[str, int]` also works

**Comment by Bam4d** [comment]
> Unique (on that timestep)

Not sure if this is true. what happens if several entities share the same ID across a batch, the indexing will become corrupted when merging/extending Observations/Batches? It definitely did before. How are we handling this case now?

**Comment by Bam4d** [comment]
> * There are still no provisions for tracking entities across timesteps. I think this will add quite a bit of additional complexity (for implementation and `VecEnv` interface, but not the `Environment` interface)  and the correct data structures aren't clear to me yet. This will likely be a substantial project of its own and is probably best tackled at a later time.

Is this not handled by the batching operations? As long as the IDS are unique for entities, things get ordered correctly. Maybe need to write a test to prove this.

**Comment by cswinter** [comment]
The EntityID's are tracked separately for each environment/timestep. So say we have two environments, we might end up with something like this:

```python
ids= [
    {"robot": [("Robot", 0)], "mine": [("Mine", 1)]},
    {"robot": [("Robot", 0), ("Robot", 1)], "mine": [("Mine", 1)]},
]
actor_ids = [
    {"move":  [("Robot", 0)]},
    {"move":  [("Robot", 0), ("Robot", 1)]},
]
```

Assuming that the obs space is ordered `["mine", "robot"]`, we then end up with the following mapping of IDs to indices:
```python
id_to_idx = [
    {
        ("Mine", 0): 0,
        ("Robot", 0): 1,
    },
    {
        ("Mine", 4): 0,
        ("Robot", 0): 1,
        ("Robot", 1): 2,
    },
]
actor_idx = {
    "move": [
        [1],
        [1, 2],
    ]
}
# RaggedI64 for index of entity corresponding to `ids` above, this is not actually materialized by the ` VecEnv` since it's implicit in the shape of the features
idx = [
    [0, 1],
    [0, 1, 2],
]
```

The indices are unique per sequence but not unique per batch since we are still going to join/shuffle the sequences anyway. We do eventually calculate flat indices that are unique per batch during the network forward pass by adding the cumulative number of entities to each sequence ([this happens in rogue_net](https://github.com/entity-neural-network/incubator/blob/11f0f60de24102af4356c9738cbb9793ea6aa334/rogue_net/rogue_net/actor.py#L64)). The `VecEnv` doesn't have to care about this since it all happens outside of the environment interface:

```python
offsets = [0, 2]
flat_actor_idx = {
    "move": [1, 3, 4]
}
flat_idx = [0, 1, 2, 3, 4]
```

**Comment by cswinter** [comment]
> > * There are still no provisions for tracking entities across timesteps. I think this will add quite a bit of additional complexity (for implementation and `VecEnv` interface, but not the `Environment` interface)  and the correct data structures aren't clear to me yet. This will likely be a substantial project of its own and is probably best tackled at a later time.
> 
> Is this not handled by the batching operations? As long as the IDS are unique for entities, things get ordered correctly. Maybe need to write a test to prove this.

So at the level of `Environment`, we do have the information to construct the right data structures, but the information is erased by `VecEnv`, which only retains indices and not IDs. We'd probably need to construct a second set of indices here that maps each entity to a slot in a "memory bank" that persists information across timesteps, but until we know how this would be implemented by the network architecture, it's a little unclear as to how exactly that should look like.

**Comment by Bam4d** [comment]
Right ok makes more sense now. we don't actually know which entities from which environment when we are at the batch level... but can assume that the indexes acrosss the sequence is consistent.

**Comment by cswinter** [comment]
Most of the ideas discussed here have been incorporated into https://github.com/entity-neural-network/incubator/pull/166. If we want to make any additional changes, it will be easier to keep track of those in new issues.
