### ISSUE TITLE
[api] Semantics of done/reward/reset

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#24]
There are a few subtleties around the semantics of observations with regards to done/reward features when an episode ends and the reset method. Current API doesn't specify consistent semantics. Haven't really thought about these details before so would be good to get input from someone who has. We should probably stick with whatever the prevailing convention is in other frameworks.

1. Should environments reset automatically at the end of an episode?
2. Should it be possible to observe the state at the end of the episode? No more actions can be taken, but might still be useful for debugging or logging stats.
3. Should the observation that returns `done=True` and the final `reward` also return the observed entities for the next episode?

Currently, the example envs will return the entities visible in the final observation at the end of the episode, and further calls to `act` are sort of undefined.

I made the `EnvList` automatically reset environments at the end of the episode and include the observation from the next episode because that's what's most convenient for the PPO training loop, but it's unclear to me whether that is the right semantics and the right place for that code to live.

https://github.com/entity-neural-network/incubator/blob/be33cae8355d0f79374718e2293983bfc5827779/entity_gym/entity_gym/environment.py#L247-L254

**Comment by Theomat** [comment]
For a single environment (not a `VecEnv`). For 1. at least, I believe this typically falls in the use case of a gym `Wrapper`, it depends on what people would like to do, and a `Wrapper` that enables automatic reset sounds like a good idea. Done this way, I believe this implies no for 3, well at least not in the general case but probably for the `Wrapper`.

Now when we want to extend to a `VecEnv`, I could see two options:

1. When we wrap a `VecEnv` the `Wrapper` is cloned/applied to every environment of the list so we can still get all the modular power of wrappers.
2. The main use case from my experience of `VecEnv` is when training, thus you want to do a lot of episodes and it could be annoying to do the reset yourself, so enable it by default or provide a boolean parameter to enable/disable automatic reset.

I am in favor of 1. but I would very much like others to pitch in.

**Comment by cswinter** [comment]
The way `VecEnv` is currently used is as the low-level interface to ENN PPO that enables maximum performance. As such, it's consistent to assume automatic environment resets. This expectation is documented in https://github.com/entity-neural-network/incubator/pull/223.
