### ISSUE TITLE
EntityID should support arbitrary objects

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#74]
Fix the `ids` field on `Observation`/`BatchObs` to allow the `EntityID`s to be arbitrary objects, and add a new test that makes sure we don't break that property.

**Comment by Bam4d** [comment]
@cswinter When we say "arbitrary objects" here do we still want things to be numerical/hashable.

There's a few places in the code taht assume thes IDs are indexes of actual entities. I guess the simplest thing to do is to just keep a map of generic EntityID to an index (which is then used for the actors etc)?

**Comment by cswinter** [comment]
It doesn't need to be anything. Internally, the train/network code just uses the index of each entity in the observation as its identifier. There's a single place in train.py that translates these indices into the corresponding EntityIDs when passing actions to the environment:

https://github.com/entity-neural-network/incubator/blob/2dbfd69f3ee1df61bd8f8a84b8081ee2ef5c6cdd/enn_ppo/enn_ppo/train.py#L316-L330

I'm not actually sure where else it's using EntityIDs, but it should be using the indices there as well.

**Comment by cswinter** [comment]
The `actors` array on the action mask is currently assumed to be an index though 🤔

**Comment by Bam4d** [comment]
Yes thats that bit I'm currently looking at. (this then goes into a ragged tensor etc.)

So we need t map that to an index in the same way as above?

**Comment by cswinter** [comment]
Yes, you're right, I think we need another translation layer there that allows the environment to specify actors in terms of `EntityID` and which then get translated into corresponding indices. So the `EntityID` actually might have to be hashable or at the very least comparable. We'll likely also want a way of letting environments just pass/accept the indices directly rather than `EntityID` to allow for higher efficiency.

Heads up, I'm about to merge https://github.com/entity-neural-network/incubator/pull/109 which changes a fair amount of the code related to action masks and that translation layer.

**Comment by Bam4d** [comment]
I guess we can just push `next_obs.ids` into `get_action_and_auxiliary` and re-map the indexes

**Comment by Bam4d** [comment]
> I guess we can just push `next_obs.ids` into `get_action_and_auxiliary` and re-map the indexes

This logic is now in a totally different place so nope :D

**Comment by Bam4d** [comment]
@cswinter how are we currently sure that the order of the EntityIDs in Observation.ids correspond to the indexd of ids once we have done the batch_and_embed function? which iterates through the entities and flattens them out into the `x` variables. The order that the entity names are iterated through is not ordered right?

**Comment by cswinter** [comment]
Python dicts have guaranteed iteration order, everything is ordered by the dict returned by the `obs_space` method. Which is quite tenuous, it would be good to find a better way of encoding that constraint.

**Comment by Bam4d** [comment]
> Python dicts have guaranteed iteration order.

I spend too much time in c++ clearly.

I will try to find a way to make this a bit cleaner

**Comment by Bam4d** [comment]
I propose that the Ids are split by their entity name so its much easier to map them to the entity (which will be the same order as the nd.array? Then we can also return ids in a consistent order to the `x` that returns from `batch_and_embed`.

Does that sound like a good idea?  

```
@dataclass
class Observation:
    entities: Dict[str, np.ndarray]
    """Maps each entity type to an array with the features for each observed entity of that type."""
    ids: Dict[str, Sequence[EntityID]]
    """
    Maps each entity index to an opaque identifier used by the environment to
    identify that entity.
    """
```

**Comment by cswinter** [comment]
SGTM. We could also consider joining the two dicts to enforce they have the same keys, so `entities: Dist[str, Tuple[npt.NDArray[np.float32], Sequence[EntityID]]`

**Comment by Bam4d** [comment]
So I had some time to work on this in the week and I think its much easier to leave the API as-is, and leave it up to environments to provide the sequence of IDS to line up with the sequence of entities.

The masks *have to* line up when the transformer/masking/pooling operations are taking place anyway, and then when actions are generated, finding the correct entityID in a map of entityIDS is more complicated as the algorithm would have to search through the entities and indexed masks seperately to try and get the entityID correctly.

Its simpler and more efficient in my opinion to ask the environments to generate the entityID list in the order of the entitiy->feature map and leave the majority of the code as-is.

Griddly now generates the entityID list and entity->feature map in this way.

**Comment by cswinter** [comment]
Ah yeah, the action masks have to be lined up as well. I still think there's probably a way to figure out an inefficient interface that's easier for environments to implement, but might not be worth the effort for now.

**Comment by Bam4d** [comment]
I'll close this for now.
