### ISSUE TITLE
Eliminate `EpisodeStats`

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#75]
The `Observation` and `ObsBatch` types have an `end_of_episode_info` field that environments can populate with an `EpisodeStats` containing the episode length and total reward at the end of an episode. Currently, every environment has to reimplement that functionality if it wants to export stats. We should remove this field and collect this information automatically over multiple timesteps in a generic env wrapper or directly in enn_ppo/train.py.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this, but I'm still learning about contributing to open source so I would probably need a bit of time and help. Would that be ok?

**Comment by cswinter** [comment]
Yes, of course! Feel free to open an issue if you have any questions, or ask [on the discord](https://discord.com/invite/SjVqhSW4Qf).

**Comment by cswinter** [comment]
@Carlosbogo We now have increasingly robust instructions for how to set up your dev environment in [CONTRIBUTING.md](https://github.com/entity-neural-network/incubator/blob/main/CONTRIBUTING.md), and if you run into any issues with it folks be happy to help figure it out and refine our process.
We've also accumulated quite a few starter issues of varying difficulty: [label:good first issue](https://github.com/entity-neural-network/incubator/labels/good%20first%20issue)
If you're unsure how to get started on a task or the best way to go about it you can always ask on the issue or create a new one, very basic questions totally fine 😄

**Comment by Carlosbogo** [comment]
Sorry for the delay, I'm pretty low on time right now as it's exam season, so I'm trying to learn and to find what to do whenever I can.

Just wanted to let you know just in case you need this solved quickly or something like that, it will probably still take me some time.

**Comment by Bam4d** [comment]
With current environments, this is not blocking anything. I don't think it needs to be solved quickly :)
