### ISSUE TITLE
Push mask and observation generation for Griddly environments to c++

### ISSUE THREAD

**Issue by Bam4d** [entity-neural-network/incubator#83]
Further to #14 its clear that the bottleneck is stepping the environment.

![image](https://user-images.githubusercontent.com/1370765/144447395-12f014b2-cc03-483a-8a2c-b79d512a43dc.png)
 (the highest line is the environment step)
 
 There's alot of redunacy in generating masks and entities in the correct format for entity observations. All of this logic can be significantly reduced if it is done in the c++ wrapper instead of generating state dictionaries and then leaving python to calculate masks etc for each object.

**Comment by cswinter** [comment]
Another potential issue is the batching performed by `ListEnv`, which is included in the "step" time. In principle, this could be pushed all the way down by implementing `VecEnv` directly:

https://github.com/entity-neural-network/incubator/blob/8f97ac7f38c3883a38e6606f7091229a332fa9a0/entity_gym/entity_gym/environment.py#L100

Though for other environments "step" is much less of a bottleneck, so this probably only accounts for a smaller fraction here.
