### ISSUE TITLE
episodic_return metric is biased

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#95]
https://github.com/entity-neural-network/incubator/pull/93 fixed a bias in the episodeic_return metric that overweighted environments with a lower index in the `VecEnv`, but in the process introduced a different bias that overweights environments that finish their episode on a global step at which fewer other environments finish their global step.

**Comment by vwxyzjn** [comment]
On a related note. I think the most correct implementation given non-iid environments is to record the episodic return for each env like `charts/episodic_return/env[i]`
