### ISSUE TITLE
W&B chokes on new high resolution episodic_reward metric

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#98]
Unfortunately, W&B doesn't seem to be able to cope with the new high-resolution episodic_reward metric added in https://github.com/entity-neural-network/incubator/pull/97. There's a massive lag on metrics, and the W&B process takes many minutes to finish after even a short run completes.

**Comment by vwxyzjn** [comment]
Hmm I ran it on my m1 mac mini and things seem to be ok. https://wandb.ai/entity-neural-network/enn-ppo/runs/1oth4wvx?workspace=user-costa-huang Maybe just a fluke?

**Comment by cswinter** [comment]
What if you run for 1000000 steps?

**Comment by vwxyzjn** [comment]
Ongoing here https://wandb.ai/entity-neural-network/enn-ppo/runs/3et4413g?workspace=user-costa-huang

**Comment by cswinter** [comment]
I can still reproduce the issue on e82e9628a8d7f62a7e483f895499c95d20841b44 with this command: 

```
poetry run python enn_ppo/enn_ppo/train.py --total-timesteps=1000000 --track --gym-id=NotHotdog --num-envs=64 --max-log-frequency=1000
```

Run already made it to 600,000 steps, but W&B has less than 30,000 datapoints

![image](https://user-images.githubusercontent.com/12845088/144755297-1906bd6c-9104-48a4-ae6a-1525e25b9b83.png)

I merged a quick fix with https://github.com/entity-neural-network/incubator/pull/99 by just subsampling 1000x. A better solution might be to log the average over each rollout, though that also has some unfortunate interactions with smoothing across steps when the number of finished episodes within each rollout has high variance.

**Comment by vwxyzjn** [comment]
@cswinter I was able to reproduce the same issue. Yeah... the envs run too fast and pop out too much data haha XD

**Comment by cswinter** [comment]
Current solution seems adequate.
